server:
  http:
    port: 9080
  grpc:
    port: 9095
positions:
  filename: /tmp/positions.yaml
clients:
  - url: http://loki:3100/loki/api/v1/push
scrape_configs:
  - job_name: flask_logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: flask_app
          __path__: /var/log/flask/*.log